# Generated by Django 2.2.28 on 2026-03-13 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug_name', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='game_images')),
                ('date_released', models.DateField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug_title', models.SlugField(unique=True)),
                ('time', models.TimeField()),
                ('video_url_id', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUSpeedruns.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUSpeedruns.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug_title', models.SlugField()),
                ('content', models.CharField(max_length=400)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUSpeedruns.Run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUSpeedruns.UserProfile')),
            ],
        ),
    ]
