# Generated by Django 2.2.28 on 2026-03-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUSpeedruns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
