# Generated by Django 2.2.28 on 2026-03-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUSpeedruns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='time',
            field=models.DurationField(),
        ),
    ]
