# Generated by Django 2.2.28 on 2026-03-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUSpeedruns', '0002_auto_20260305_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='time',
            field=models.TimeField(),
        ),
    ]
