# Generated by Django 2.2.28 on 2026-03-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUSpeedruns', '0002_auto_20260318_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
