# Generated by Django 2.2.28 on 2026-03-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUSpeedruns', '0003_auto_20260305_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug_title',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
