# Generated by Django 2.2.28 on 2026-03-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUSpeedruns', '0003_remove_userprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug_name',
            field=models.SlugField(default='', unique=True),
        ),
    ]
