# Generated by Django 2.2.28 on 2026-03-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUSpeedruns', '0004_userprofile_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
